name: ice_code_editor
version: 1.0.0
authors:
- Chris Strom <chris@eeecomputes.com>
- Santiago Arias <santiago.ariassar@gmail.com>
- James Hurford <terrasea@gmail.com>
- Srdjan Pejic <spejic@gmail.com>
description: Code Editor + Preview
homepage: https://github.com/eee-c/ice-code-editor
dependencies:
  browser: '>=0.10.0 <0.11.0'
  crypto: '>=0.9.0 < 0.10.0'
  ctrl_alt_foo: '>=0.3.0 <0.3.1'
  ace: ">=0.5.10 <0.5.11"
  polymer: any
dev_dependencies:
  scheduled_test: any
  unittest: '0.11.4'
transformers:
- polymer:
    entry_points: web/polymer.html
